### ISSUE TITLE
Create a new Recommend Reward page

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#158]
**What's the improvement**:

1. Create a new page inside the Benefits page where we reference the benefit all users have when recommending us a pub.
1. Change all references to "Deals" to "Benefits"

**How should it look like (screenshot or sketch)**:

![Birthday Gift Proposal Page 002](https://user-images.githubusercontent.com/39112974/56847436-c049e580-68d2-11e9-948e-3499639560e0.jpeg)

**How should it work (write use case)**:

- When users click on the button to recommend a pub, it will take them to the Google Form for recommending a pub: https://docs.google.com/forms/d/e/1FAIpQLSfr2dEghUT1VF1i9BWPsvZIJpnHe2FPVmCuoHJaAR3AXDe_GA/viewform

**Priority (tag accordingly):** `regular` 
**Domain (tag accordingly):** `frontend`
**Branch**: `create-a-new-recommand-gift-page`

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by buckwierd** [comment]
@RohrerHope I had to unassign myself because the first step needs to be done by Loic. He will then unassign himself and assign me to it. 

Assigning both of us at the same time, will create confusion.

**Comment by lcoenen** [comment]
@buckwierd, @RohrerHope commented on the wrong issue: https://github.com/Whichost/frontend/issues/160#issuecomment-487306937 

He have drafted a T&C page here:

https://docs.google.com/document/d/10QJIkSMLU4r8v7wvVFh0uDZcrAquUya4DgVCsKmgRMY/edit#

**Comment by lcoenen** [comment]
**What have been done**: We created the Recommand Gift
**Pushed to**: `create-new-recommend-gift-page`
**Tag somebody**: @buckwierd 

All yours. Also, @RohrerHope what about we call them Recommand Reward? The "Recommend Gift" wording sounds odd imho.

**Comment by RohrerHope** [comment]
Naming it Recommend Reward sounds good.

Thanks.

**Comment by buckwierd** [comment]
**What has been done:** Populated the Recommend Reward page. Amended the translation to "Recommend Reward".
**Pushed to:** Not pushed yet
**Tag somebody:** @lcoenen 

Waiting for Loic to provide further instructions for:
I pulled the origin and I can’t see the branch `add-benefits-terms-in-a-legal-page`. Do I have to create it, like I created yesterday the `hotfix-fix-pricing-inside-pub-fees`branch locally?

**Comment by lcoenen** [comment]
@buckwierd please let me get back to you on this.

**Comment by lcoenen** [comment]
@buckwierd This issue (#158) is fixed if you created the new Recommend Reward page. Talks about the terms and conditions are related to #160 .

**Comment by buckwierd** [comment]
Done. PR will follow.

**Comment by RohrerHope** [comment]
**What's wrong**: 

The T&Cs link opens a 404 and it opens in a new tab.

**How it should be**: 

T&Cs should open the actual T&Cs and it should open in the same tab.

I moved the corresponding card to `Still have issues` column on the board and I reopen the issue.

**Comment by lcoenen** [comment]
**What have been done**: We fixed the link 
**Pushed to**: `create-new-recommend-gift-page`
**Tag somebody**: @RohrerHope 
**PR**: 

**Note**: 

Due to a limitation in the NamedLink system, we cannot use anchors. That means that the T&C links will redirect to the top of the T&C page. It's on you to decide if we should delay the launch or just create a new issue and fix it next time. 

Also, don't worry about the size of the left panel, it have been fixed in #157.

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Comment by RohrerHope** [comment]
@lcoenen 

If possible, please update the top phrase to "Earn a gift card to use with over 2,000 shops in Ireland & the UK!"

Why? Because in our T&C we indicate that the benefit is for both countries and because One4all work also in the UK.

If not possible, then I'll create a new hot fix issue after this push to master.

Thanks.
